runtime: nodejs16  
env: standard  

handlers:
  - url: /static
    static_dir: build/static
  - url: /favicon.ico
    static_files: build/favicon.ico
    upload: build/favicon.ico
  - url: /.* 
    script: auto
